num_loops: 20
storage_capacity: 50

batch_size: 15
batch_repeat_size: 2

num_workers: 10

steps: 3000
save_start: 100
save_step: 150

lr:
  init: 0.00001
  anneal_step: 20
  anneal_rate: 0.99

grad_max_norm: 10.0  
weight_decay: 0.0001

beta:
  cons:
    mode: "sigmoid"
    min: 0.0001
    max: 0.001
    warmup: 1000
    anneal_period: 2000
  var:
    mode: "sigmoid"
    min: 0.000001
    max: 0.000005
    warmup: 1000
    anneal_period: 2000