batch_size: 20
batch_repeat_size: 2

steps: 40000
save_start: 5000
save_step: 1000

lr:
  init: 0.001
  anneal_step: 30
  anneal_rate: 0.99

grad_max_norm: 10.0  
weight_decay: 0.0001

beta:
  cons:
    mode: "sigmoid"
    min: 0.00001
    max: 0.001
    warmup: 3000
    anneal_period: 10000
  var:
    mode: "sigmoid"
    min: 0.000001
    max: 0.000005
    warmup: 3000
    anneal_period: 10000